### ISSUE TITLE
unregisterCollisionBox not working =(

### ISSUE THREAD

**Issue by Gavolot** [bawat/AStarMultithreaded#1]
unregisterCollisionBox not working =(

![image](https://user-images.githubusercontent.com/3579229/94329469-c9594d80-ffc3-11ea-9943-5a1d91a3cc98.png)

i read your code and tried to detect it, but it doesn't work = (((i tried everything

**Comment by bawat** [comment]
Hello Gavolot!

I've updated the Yoyogames forum link to the newest compiled version to avoid future confusion.
After downloading the new .DLL, the unregister function should now exist.
I've also updated the example file.

Hope this helps,
Bawat
